# Generated by Django 4.2.19 on 2025-02-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (1, "Family"),
                            (2, "Friends"),
                            (3, "Work"),
                            (4, "Trade"),
                            (5, "Other"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
