# Generated by Django 4.2.19 on 2025-02-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Family"),
                    (2, "Friends"),
                    (3, "Work"),
                    (4, "Trade"),
                    (5, "Other"),
                ]
            ),
        ),
    ]
