# Generated by Django 4.2.19 on 2025-02-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_contact_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="type",
            field=models.CharField(
                choices=[
                    ("1", "Family"),
                    ("2", "Friends"),
                    ("3", "Work"),
                    ("4", "Trade"),
                    ("5", "Other"),
                ],
                max_length=2,
            ),
        ),
    ]
